name: mongo-sharding-repl

services:
  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv
    command:
      - --configsvr
      - --replSet
      - config_server
      - --bind_ip_all
      - --port
      - "27019"
    volumes:
      - configSrv_data:/data/db

  # ═══ Replica Set: shard1 ═══
  shard1-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-1
    command:
      - --shardsvr
      - --replSet
      - shard1
      - --bind_ip_all
      - --port
      - "27018"
    volumes:
      - shard1_1_data:/data/db

  shard1-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-2
    command:
      - --shardsvr
      - --replSet
      - shard1
      - --bind_ip_all
      - --port
      - "27018"
    volumes:
      - shard1_2_data:/data/db

  shard1-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-3
    command:
      - --shardsvr
      - --replSet
      - shard1
      - --bind_ip_all
      - --port
      - "27018"
    volumes:
      - shard1_3_data:/data/db

  # ═══ Replica Set: shard2 ═══
  shard2-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-1
    command:
      - --shardsvr
      - --replSet
      - shard2
      - --bind_ip_all
      - --port
      - "27018"
    volumes:
      - shard2_1_data:/data/db

  shard2-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-2
    command:
      - --shardsvr
      - --replSet
      - shard2
      - --bind_ip_all
      - --port
      - "27018"
    volumes:
      - shard2_2_data:/data/db

  shard2-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-3
    command:
      - --shardsvr
      - --replSet
      - shard2
      - --bind_ip_all
      - --port
      - "27018"
    volumes:
      - shard2_3_data:/data/db

  mongos_router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router
    command:
      - mongos
      - --configdb
      - config_server/configSrv:27019
      - --bind_ip_all
      - --port
      - "27017"
    ports:
      - 27017:27017
    depends_on:
      - configSrv
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3

  pymongo_api:
    image: kazhem/pymongo_api:1.0.0
    container_name: pymongo_api
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  configSrv_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:
